name: Call API a cada 1 minuto

on:
  schedule:
    - cron: '*/1 * * * *'  # Executar a cada minuto

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
    - name: Chamada para a API
      run: curl -X GET ${{ secrets.API_URL }}
