name: Call API each minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Each minute

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
    - name: Call for the API
      run: curl -X GET ${{ secrets.API_URL }}
